version: "3.9"
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2:/var/lib/influxdb2
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - "influxdb"
