version: "3.9"
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2:/var/lib/influxdb2
      - ./influx-startup.sh:/docker-entrypoint-initdb.d/influx-startup.sh
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
