Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.synced_folder '.', '/vagrant', disabled: false
  
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.network "forwarded_port", guest: 8086, host: 8086
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provision "shell", inline: <<-SHELL
     # Install Docker
     yum install -y yum-utils
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install -y docker-ce docker-ce-cli containerd.io

     # Post install
     usermod -aG docker vagrant

     # Docker-compose
     curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     chmod +x /usr/local/bin/docker-compose

     # Start docker
     systemctl start docker
   SHELL
end
