version: "3.9"
services:
  db:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - .:/var/lib/influxdb2
  monitoring:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
